# Generated by Django 4.0.1 on 2022-01-24 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthCertNumber',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherName',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobilePhone2',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='motherName',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(choices=[('bd', 'Bangladeshi'), ('in', 'Indian'), ('ng', 'Nigerian'), ('ug', 'Uganda'), ('cn', 'chaina')], default='bd', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanentAddress',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default-user-avatar.png', upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='presentAddress',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
