# Generated by Django 4.0.1 on 2022-01-24 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birthcertnumber_user_fathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobilePhone2',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Secondary phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanentAddress',
            field=models.CharField(max_length=1024, null=True, verbose_name='Parmanent Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='presentAddress',
            field=models.CharField(max_length=1024, null=True, verbose_name='Present Address'),
        ),
    ]
