# Generated by Django 3.2.9 on 2021-12-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_auto_20211203_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveBigIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=14, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('blood_group', models.CharField(max_length=3, null=True)),
                ('guardian_name', models.CharField(max_length=100, null=True)),
                ('guardian_phone', models.IntegerField(max_length=14, null=True)),
                ('guardian_email', models.EmailField(max_length=100, null=True)),
                ('present_address', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
        ),
    ]
