# Generated by Django 3.2.9 on 2021-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
    ]
