# Generated by Django 3.2.9 on 2021-12-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_nobin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nobin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nobin',
            name='updated_at',
        ),
    ]
