# Generated by Django 3.2.9 on 2021-12-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20211201_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nobin',
        ),
    ]
