# Generated by Django 3.2.9 on 2021-12-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_delete_nobin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveBigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date time created at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date time updated at'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date time created at'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date time updated at'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date time created at'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date time updated at'),
        ),
    ]
